server:
  port: 8080
  servlet:
    context-path: /familyhealth
spring:

  ai:
    openai:
      api-key: AIzaSyAmYgRbDrp8PtYdrMPoF2CrE7DRmx4Gf0M
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
      embedding:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/familyhealth
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
jwt:
  expiration: 2592000
  secretKey: NoGqvbiTkYcVvArxFI36DjCPjgQOIFo/962T4QO3fm8=

vnpay:
  tmnCode: HAQLDG05
  hashSecret: KEKR6R8HEUOV0GPYPPZ8HMWM8QPA2AO8
  pay_url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return_url: http://localhost:8080/familyhealth/api/payments/vnpay-callback

frontend:
  url: http://localhost:3000

zalopay:
  app_id: 2554
  key1: sdngKKJmqEMzvh5QQcdD2A9XBSKq80v0
  key2: trMrHtvjo6myautxDUiAcYsVtaeQ8nhf
  pay_url: https://sb-openapi.zalopay.vn/v2/create
  return_url: http://localhost:8080/familyhealth/api/payments/zalopay-callback

momopay:
  partner_code:
  access_key:
  secret_key:
  pay_url: https://test-payment.momo.vn/gw_payment/transactionProcessor
  return_url: http://localhost:8080/familyhealth/api/payments/momo-callback

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: familyhealth
    title: Familyhealth API Documentation
    version: v1.1.0
    serverUrl: http://localhost:${server.port}/familyhealth

report:
  output:
    directory: d:/reports


