server:
  port: 8080
  servlet:
<<<<<<< HEAD
    context-path: /familyhealth
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/familyhealth
=======
    context-path:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goexplore
>>>>>>> f3ef2a1816e0a6ceed82d37f450c23fd4ce4c822
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
